### PR TITLE
Add CMake build system to PENF

### PR DESCRIPTION
**Pull request by victorsndvg**
- Split penf.F90 file into several files (one per module)
- Add CMake compilation system
- Update f90 extension in fobos file

### CODE REVIEW

**Comment by szaghi** [comment]
@victorsndvg Thank you!

**Comment by victorsndvg** [comment]
Dear @szaghi ,

let me know if you see any issue in the PR. 
I think it will be very easy to fix anithing :)

I always use the same folder hierarchy and almost the same CMake scripts. If you have any question about the compilation system I can explain you in a higher detail.

**Comment by szaghi** [comment]
@victorsndvg Just one question: why you change the extension of `penf.F90` to lower case? It seems that in your `penf.f90` thare are still pre-processing directive.

**Comment by victorsndvg** [comment]
@szaghi ,

I know that `.F90` extension is a convention about pre-processing... but only for unix/linux!(?)

This is what i've understood in this post:
http://fortranwiki.org/fortran/show/File+extensions 

I can change it (really fast) if you want!

**Comment by szaghi** [comment]
@victorsndvg I know this is a convention and not a _standard_, but many compilers (and FORD) adopt it. I do not remember exactly when/why (I was sure that you was the one that corrected my addiction to adopt always `.f90` :smile: ), but I currently prefer to make explicit that those files have pre-processing flags by the upper case extension. If this does not matter for you, I prefer to stay with this convention.

**Comment by victorsndvg** [comment]
Ok! I go with it! :+1:

**Pull request closed without merging**
